stages:
  - build
  - push
  - deploy
  - test

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/reverse-proxy-nginx
  KUBECONFIG: /root/.kube/config
  K8S_NAMESPACE: default
  K8S_CONTEXT: minikube # Ubah sesuai konteks Kubernetes cluster Anda

before_script:
  - apk add --no-cache docker curl git bash
  - echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config

# Step 1: Build Docker Image
build-image:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
  only:
    - main

# Step 2: Push Image to GitLab Container Registry
push-image:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
  dependencies:
    - build-image

# Step 3: Deploy to Kubernetes
deploy-k8s:
  stage: deploy
  script:
    - kubectl config use-context $K8S_CONTEXT
    - kubectl apply -f config-kubernetes.yaml
  only:
    - main
  dependencies:
    - push-image

# Step 4: Testing and Validation
test-deployment:
  stage: test
  script:
    - sleep 30 # Allow time for deployment
    - kubectl get pods
    - curl -v http://example.com
  only:
    - main
  dependencies:
    - deploy-k8s
